server:
  port: 8085
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 198855
    url: jdbc:postgresql://localhost:5432/postgres
yandex:
