server:
  port: 8085
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: snuser
    password: snpassword
    url: jdbc:postgresql://81.177.6.228:5432/socialnet